config/routes.rb
Rails.application.routes.draw do

  devise_for :admins, :controllers => { registrations: 'admin/registrations'}

  devise_for :users, :controllers => { registrations: 'registrations' }

  resources :instructor_courses

  resources :notes

  resources :attendances

  resources :students

  resources :instructors

  resources :courses do
    resources :students
    member do
      get 'manage'
    end
  end
  get "/courses/:id/calendar" => "courses#calendar" 
  root 'static#home'

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: :show

  def index
    @courses = Course.all
  end

  def show
    @today_data = TodaySort.new(params[:id]).run
  end

  def calendar
    # @admin = Admin.find_by(:id => @course.instructor)
    date1 = params[:dateone].to_date
    date2 = params[:datetwo].to_date
    week = Range.new(date1, date2)
    @table_data = Calendar.new(params[:id], week).run
  
    render layout: false
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def manage
    @course = Course.find(params[:id])
    @student = Student.new
    @student_course = StudentCourse.new
  end

  def create
    @course = Course.create(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @course = Course.find(params[:id])
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_course
      @course = Course.find(params[:id])
    end


    def course_params
      params.require(:course).permit(:name, students_attributes: [:id, :first_name, :last_name, :_destroy])
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/.show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/base/jquery-ui.css">
<script type="text/javascript">
$(function() {
    var startDate;
    var endDate;
    
    var selectCurrentWeek = function() {
        window.setTimeout(function () {
            $('.week-picker').find('.ui-datepicker-current-day a').addClass('ui-state-active')
        }, 1);
    }

    var  queryDatabase = function(startDate, endDate) {
          $.get("/courses/1/calendar?dateone=" + startDate + "&datetwo=" + endDate, function(html) {
            $(".rwd-table").replaceWith(html);
          }
        )}
    
    $('.week-picker').datepicker( {
        showOtherMonths: true,
        selectOtherMonths: true,
        onSelect: function(dateText, inst) { 
            var date = $(this).datepicker('getDate');
            startDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay());
            endDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 6);
            var dateFormat = inst.settings.dateFormat || $.datepicker._defaults.dateFormat;
            $('#startDate').text($.datepicker.formatDate( dateFormat, startDate, inst.settings ));
            $('#endDate').text($.datepicker.formatDate( dateFormat, endDate, inst.settings ));
            
            selectCurrentWeek();
            queryDatabase(startDate, endDate);
        },
        beforeShowDay: function(date) {
            var cssClass = '';
            if(date >= startDate && date <= endDate)
                cssClass = 'ui-datepicker-current-day';
            return [true, cssClass];
        },
        onChangeMonthYear: function(year, month, inst) {
            selectCurrentWeek();
        }
    });
    
    $('.week-picker .ui-datepicker-calendar tr').live('mousemove', function() { $(this).find('td a').addClass('ui-state-hover'); });
    $('.week-picker .ui-datepicker-calendar tr').live('mouseleave', function() { $(this).find('td a').removeClass('ui-state-hover'); });
});
</script>
</head>
<body>

    <div class="l-content">
        <div class="pricing-tables pure-g">
            <div class="pure-u-1 pure-u-md-1-3">
                <div class="pricing-table pricing-table-free">
                    <div class="pricing-table-header">
                        <h2>//</h2>

                        <span class="pricing-table-price">
                            in <span></span>
                        </span>
                    </div>

                    <ul class="pricing-table-list">
                        <% @today_data[:here].each do |student| %>
                        <li><%= student %></li>
                        <% end %>
                    </ul>

                </div>
            </div>

            <div class="pure-u-1 pure-u-md-1-3">
                <div class="pricing-table pricing-table-biz pricing-table-selected">
                    <div class="pricing-table-header">
                        <h2>today</h2>

                        <span class="pricing-table-price">
                            late <span></span>
                        </span>
                    </div>

                    <ul class="pricing-table-list">
                        <% @today_data[:late].each do |student| %>
                        <li><%= student %></li>
                        <% end %>
                    </ul>
                </div>
            </div>

            <div class="pure-u-1 pure-u-md-1-3">
                <div class="pricing-table pricing-table-enterprise">
                    <div class="pricing-table-header">
                        <h2>//</h2>

                        <span class="pricing-table-price">
                            out <span></span>
                        </span>
                    </div>

                    <ul class="pricing-table-list">
                        <% @today_data[:out].each do |student| %>
                        <li><%= student %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div> <!-- end pricing-tables -->



    <div class="row">
  <div class="col-md-4"><h1>here</h1>
    <% @today_data[:here].each do |student| %>
    <%= student %><br>
    <% end %>
    </div>
  <div class="col-md-4"><h1>late</h1>
    <% @today_data[:late].each do |student| %>
    <li><%= student %></li>
    <% end %></div>
  <div class="col-md-4"><h1>out</h1>
    <% @today_data[:out].each do |student| %>
    <li><%= student %></li>
    <% end %></div>
  </div>
  <br />
  <br />
  <br />
  <br />
  <br />
    </div>
    <div class="week-picker"></div>
    <br /><br />
    <div class="show-week">
    <label>Week :</label> <span id="startDate"></span> - <span id="endDate"></span>
    </div>
    <table class="rwd-table"></table>
</body>
</html>

app/views/courses/_form.html.erb
<%= simple_form_for @course do |f| %>
  
  <h3>Students</h3>
  <div id='students'>
<!--     <%= f.simple_fields_for :students do |student| %>
      <%= render 'student_fields', :f => student %>
    <% end %> -->
    <div class='links'>
      <%= link_to_add_association 'add student', f, :students %>
    </div>
  </div>
    <%= f.button :submit, 'Save' %>
<% end %>

app/views/courses/_student_fields.html.erb
<div class='nested-fields'>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= link_to_remove_association "remove student", f %>
</div>

app/views/courses/calendar.html.erb
<table class="student-table" style="margin: auto;">
  <tr>
    <th>name</th>
    <th>monday</th>
    <th>tuesday</th>
    <th>wednesday</th>
    <th>thursday</th>
    <th>friday</th>
  </tr>
    <% @table_data.each_pair do |key, student_data| %>
      <tr>
        <td><%= student_data[:name] %></td>
        <td><%= student_data[:monday] %></td>
        <td><%= student_data[:tuesday]%></td>
        <td><%= student_data[:wednesday]%></td>
        <td><%= student_data[:thursday]%></td>
        <td><%= student_data[:friday]%></td>
      </tr>
    <% end %>
</table>

app/views/courses/index.html.erb
<html>
<head>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid" id="button">
        <div class="navbar-header">
          <a class="navbar-brand" href="#"><%= current_admin.first_name%></a>
         </div>
       <div>
       <ul class="nav navbar-nav navbar-right">
          <li class="active"><a href="#">Home</a></li>
          <% if !admin_signed_in? %>  
            <li><%= link_to("Log In", new_admin_session_path) %></li>
            <li><%= link_to("Sign Up", new_admin_registration_path) %></li>
          <%else%>
            <li><%= link_to("Log Out", destroy_admin_session_path, method: :delete) %></li>
          <%end%>
        </ul>
      </div> 
    </div>
  </nav>
 
  <div class= "tree"></div>
 

app/views/courses/manage.html.erb
 <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title><%= @course.name %></title>
</head>
<body>
<%= render 'form' %>
</body>
</html>

app/views/courses/new.html.erb
<div class="container">
  <%= form_for @course do |f| %>
    <%= f.text_field :name, :placeholder => "course name" %>
    <%= f.submit %>
  <% end %>
</div>

app/views/courses/show.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
<div class="container-fluid" id="button">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><%= current_admin.first_name%></a>
     </div>
   <div>
   <ul class="nav navbar-nav navbar-right">
      <li class="active"><a href="#">Home</a></li>
      <% if !admin_signed_in? %>  
        <li><%= link_to("Log In", new_admin_session_path) %></li>
        <li><%= link_to("Sign Up", new_admin_registration_path) %></li>
      <%else%>
        <li><%= link_to("Log Out", destroy_admin_session_path, method: :delete) %></li>
      <%end%>
    </ul>
  </div> 
</div>
</nav>
  
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A layout example that shows off a responsive pricing table.">


<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">



<!--[if lte IE 8]>
  
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-old-ie-min.css">
  
<![endif]-->
<!--[if gt IE 8]><!-->
  
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css">
  
<!--<![endif]-->





  
    <!--[if lte IE 8]>
        <link rel="stylesheet" href="css/layouts/pricing-old-ie.css">
    <![endif]-->
    <!--[if gt IE 8]><!-->
        <link rel="stylesheet" href="css/layouts/pricing.css">
    <!--<![endif]-->


<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.js"></script>
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/jquery-ui.min.js"></script>
    <link rel="stylesheet" type="text/css" media="screen" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.14/themes/base/jquery-ui.css">
<script type="text/javascript">
$(function() {
    var startDate;
    var endDate;
    
    var selectCurrentWeek = function() {
        window.setTimeout(function () {
            $('.week-picker').find('.ui-datepicker-current-day a').addClass('ui-state-active')
        }, 1);
    }

    var  queryDatabase = function(startDate, endDate) {
          $.get("/courses/1/calendar?dateone=" + startDate + "&datetwo=" + endDate, function(html) {
            $(".student-table").replaceWith(html);
          }
        )}
    
    $('.week-picker').datepicker( {
        showOtherMonths: true,
        selectOtherMonths: true,
        onSelect: function(dateText, inst) { 
            var date = $(this).datepicker('getDate');
            startDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay());
            endDate = new Date(date.getFullYear(), date.getMonth(), date.getDate() - date.getDay() + 6);
            var dateFormat = inst.settings.dateFormat || $.datepicker._defaults.dateFormat;
            $('#startDate').text($.datepicker.formatDate( dateFormat, startDate, inst.settings ));
            $('#endDate').text($.datepicker.formatDate( dateFormat, endDate, inst.settings ));
            
            selectCurrentWeek();
            queryDatabase(startDate, endDate);
        },
        beforeShowDay: function(date) {
            var cssClass = '';
            if(date >= startDate && date <= endDate)
                cssClass = 'ui-datepicker-current-day';
            return [true, cssClass];
        },
        onChangeMonthYear: function(year, month, inst) {
            selectCurrentWeek();
        }
    });
    
    $('.week-picker .ui-datepicker-calendar tr').live('mousemove', function() { $(this).find('td a').addClass('ui-state-hover'); });
    $('.week-picker .ui-datepicker-calendar tr').live('mouseleave', function() { $(this).find('td a').removeClass('ui-state-hover'); });
});
</script>

    <div class="l-content">
        <div class="pricing-tables pure-g">
            <div class="pure-u-1 pure-u-md-1-3">
                <div class="pricing-table pricing-table-free">
                    <div class="pricing-table-header">
                        <h2>//</h2>

                        <span class="pricing-table-price">
                            in <span></span>
                        </span>
                    </div>

                    <ul class="pricing-table-list">
                        <% @today_data[:here].each do |student| %>
                        <li><%= student %></li>
                        <% end %>
                    </ul>

                </div>
            </div>

            <div class="pure-u-1 pure-u-md-1-3">
                <div class="pricing-table pricing-table-biz pricing-table-selected">
                    <div class="pricing-table-header">
                        <h2>today</h2>

                        <span class="pricing-table-price">
                            late <span></span>
                        </span>
                    </div>

                    <ul class="pricing-table-list">
                        <% @today_data[:late].each do |student| %>
                        <li><%= student %></li>
                        <% end %>
                    </ul>
                </div>
            </div>

            <div class="pure-u-1 pure-u-md-1-3">
                <div class="pricing-table pricing-table-enterprise">
                    <div class="pricing-table-header">
                        <h2>//</h2>

                        <span class="pricing-table-price">
                            out <span></span>
                        </span>
                    </div>

                    <ul class="pricing-table-list">
                        <% @today_data[:out].each do |student| %>
                        <li><%= student %></li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div> <!-- end pricing-tables -->


    </div>
    <div class="week-picker"></div>
    <br /><br />
    <div class="show-week">
    <label>Week :</label> <span id="startDate"></span> - <span id="endDate"></span>
    </div>
    <table class="student-table"></table>